# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "linux-helloworld"
     vb.cpus = 2
     vb.memory = "2048"
  end

  config.vm.network "forwarded_port", guest: 8888, host: 18888

  # # install python
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install python3-pip -y

  #   sudo ln -s /usr/bin/python3 /usr/bin/python
  # SHELL

  # install docker
  # config.vm.provision "shell", path: "./build_scripts/install_docker.sh"
  # config.vm.provision "shell", path: "./build_scripts/install_docker.sh"

  # user application
  config.vm.synced_folder "./app", "/app"
  config.vm.provision "shell", path: "./app/001_setup.sh"

end
